### ISSUE TITLE
'Depends on' does not work when added later

### ISSUE THREAD

**Issue by lucyleeow** [napari/docs#419]
## 🐛 Bug
It seems that the 'Depends on' CI check does not work if you edit the OP later and add it, see https://github.com/napari/docs/pull/416.

Not super important though.

**Comment by brisvag** [comment]
Unfortunatelt you have to retrigger it manually (I just did it) for it to work, or push some new commit, otherwise the workflow won't run!

**Comment by psobolewskiPhD** [comment]
Could do something like the edit_pr_description:
https://github.com/napari/docs/blob/main/.github/workflows/edit_pr_description.yml

The idea being to also trigger the check when the PR description is edited.

Actually that's what the docs for the action have:
```
on:
  pull_request_target: 
    types: [opened, edited, closed, reopened]

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check Dependencies
    steps:
    - uses: gregsdennis/dependencies-action@main
      with:
        custom-domains: my-custom-domain.io another.domain.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
